### PR TITLE
Extension types, timestamp, UTF-8 fix

### LINKED ISSUE #4: Support extension types
Thanks for merging my PR so quickly!

Version 5 of the MessagePack spec supports [extensions](https://github.com/msgpack/msgpack/blob/master/spec.md#ext-format-family) (custom data types), including one that is optional but standardized: timestamp.  Currently this package decodes MessagePack data with extensions incorrectly.  It shouldn't, and it would be nice to support timestamps.  I plan to address this next.

### PR DESCRIPTION
**Pull request by dbohdan**
This PR:
* Implements extension types with pluggable unpackers (see `set_ext_unpacker`);
* Implements timestamps;
* Adds new tests from [msgpack-test-suite](https://github.com/kawanet/msgpack-test-suite/);
* Fixes `str`.  According to the spec strings must be in UTF-8.

Closes #4.

(Edited.  I submitted early.)

### CODE REVIEW

**Comment by dbohdan** [comment]
Please don't merge this for now.  I may have bugfixes.

**Comment by dbohdan** [comment]
All right, I've pushed the fix and more tests.  If you have no issues with the PR, you can merge it.

**Comment by dbohdan** [comment]
@jdc8 Could you merge this?

**Comment by jdc8** [comment]
Done, sorry for the delay.

**Comment by dbohdan** [comment]
Thanks!

**Pull request merged**
